/* eslint-disable */
// ============================================================================
// AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
// Generated by: tools/gen-permissions.mjs
//
// Purpose:
//   IDE-friendly permission constants for templates/components.
//
// Usage:
//   PERM.TeamManagement.view
//   PERM.TeamManagement.delete
// ============================================================================

export type PermPair = Readonly<{ module: string; action: string }>;

export const PERM = {
  "UserManagement": {
    "view": {
      "module": "UserManagement",
      "action": "view"
    },
    "create": {
      "module": "UserManagement",
      "action": "create"
    },
    "update": {
      "module": "UserManagement",
      "action": "update"
    },
    "delete": {
      "module": "UserManagement",
      "action": "delete"
    },
    "activate": {
      "module": "UserManagement",
      "action": "activate"
    },
    "resetPassword": {
      "module": "UserManagement",
      "action": "resetPassword"
    },
    "assignRole": {
      "module": "UserManagement",
      "action": "assignRole"
    }
  },
  "PropertyManagement": {
    "view": {
      "module": "PropertyManagement",
      "action": "view"
    },
    "create": {
      "module": "PropertyManagement",
      "action": "create"
    },
    "update": {
      "module": "PropertyManagement",
      "action": "update"
    },
    "delete": {
      "module": "PropertyManagement",
      "action": "delete"
    },
    "assign": {
      "module": "PropertyManagement",
      "action": "assign"
    },
    "upload": {
      "module": "PropertyManagement",
      "action": "upload"
    },
    "configure": {
      "module": "PropertyManagement",
      "action": "configure"
    }
  },
  "TenantManagement": {
    "view": {
      "module": "TenantManagement",
      "action": "view"
    },
    "create": {
      "module": "TenantManagement",
      "action": "create"
    },
    "update": {
      "module": "TenantManagement",
      "action": "update"
    },
    "delete": {
      "module": "TenantManagement",
      "action": "delete"
    },
    "assign": {
      "module": "TenantManagement",
      "action": "assign"
    },
    "upload": {
      "module": "TenantManagement",
      "action": "upload"
    },
    "sendNotification": {
      "module": "TenantManagement",
      "action": "sendNotification"
    },
    "recordPayment": {
      "module": "TenantManagement",
      "action": "recordPayment"
    },
    "viewHistory": {
      "module": "TenantManagement",
      "action": "viewHistory"
    },
    "terminate": {
      "module": "TenantManagement",
      "action": "terminate"
    },
    "renew": {
      "module": "TenantManagement",
      "action": "renew"
    }
  },
  "TeamManagement": {
    "view": {
      "module": "TeamManagement",
      "action": "view"
    },
    "create": {
      "module": "TeamManagement",
      "action": "create"
    },
    "update": {
      "module": "TeamManagement",
      "action": "update"
    },
    "delete": {
      "module": "TeamManagement",
      "action": "delete"
    },
    "assign": {
      "module": "TeamManagement",
      "action": "assign"
    },
    "upload": {
      "module": "TeamManagement",
      "action": "upload"
    },
    "monitor": {
      "module": "TeamManagement",
      "action": "monitor"
    },
    "generate": {
      "module": "TeamManagement",
      "action": "generate"
    },
    "lock": {
      "module": "TeamManagement",
      "action": "lock"
    },
    "unlock": {
      "module": "TeamManagement",
      "action": "unlock"
    }
  },
  "OwnerManagement": {
    "view": {
      "module": "OwnerManagement",
      "action": "view"
    },
    "create": {
      "module": "OwnerManagement",
      "action": "create"
    },
    "update": {
      "module": "OwnerManagement",
      "action": "update"
    },
    "delete": {
      "module": "OwnerManagement",
      "action": "delete"
    },
    "assign": {
      "module": "OwnerManagement",
      "action": "assign"
    },
    "upload": {
      "module": "OwnerManagement",
      "action": "upload"
    }
  },
  "AgentManagement": {
    "view": {
      "module": "AgentManagement",
      "action": "view"
    },
    "create": {
      "module": "AgentManagement",
      "action": "create"
    },
    "update": {
      "module": "AgentManagement",
      "action": "update"
    },
    "delete": {
      "module": "AgentManagement",
      "action": "delete"
    },
    "assign": {
      "module": "AgentManagement",
      "action": "assign"
    },
    "monitor": {
      "module": "AgentManagement",
      "action": "monitor"
    }
  },
  "LeaseManagement": {
    "view": {
      "module": "LeaseManagement",
      "action": "view"
    },
    "create": {
      "module": "LeaseManagement",
      "action": "create"
    },
    "update": {
      "module": "LeaseManagement",
      "action": "update"
    },
    "terminate": {
      "module": "LeaseManagement",
      "action": "terminate"
    },
    "renew": {
      "module": "LeaseManagement",
      "action": "renew"
    },
    "upload": {
      "module": "LeaseManagement",
      "action": "upload"
    },
    "monitor": {
      "module": "LeaseManagement",
      "action": "monitor"
    }
  },
  "PaymentBilling": {
    "view": {
      "module": "PaymentBilling",
      "action": "view"
    },
    "recordPayment": {
      "module": "PaymentBilling",
      "action": "recordPayment"
    },
    "create": {
      "module": "PaymentBilling",
      "action": "create"
    },
    "update": {
      "module": "PaymentBilling",
      "action": "update"
    },
    "delete": {
      "module": "PaymentBilling",
      "action": "delete"
    },
    "export": {
      "module": "PaymentBilling",
      "action": "export"
    },
    "configure": {
      "module": "PaymentBilling",
      "action": "configure"
    }
  },
  "MaintenanceRequests": {
    "view": {
      "module": "MaintenanceRequests",
      "action": "view"
    },
    "create": {
      "module": "MaintenanceRequests",
      "action": "create"
    },
    "update": {
      "module": "MaintenanceRequests",
      "action": "update"
    },
    "assign": {
      "module": "MaintenanceRequests",
      "action": "assign"
    },
    "upload": {
      "module": "MaintenanceRequests",
      "action": "upload"
    },
    "close": {
      "module": "MaintenanceRequests",
      "action": "close"
    },
    "monitor": {
      "module": "MaintenanceRequests",
      "action": "monitor"
    },
    "generate": {
      "module": "MaintenanceRequests",
      "action": "generate"
    }
  },
  "ComplianceManagement": {
    "view": {
      "module": "ComplianceManagement",
      "action": "view"
    },
    "create": {
      "module": "ComplianceManagement",
      "action": "create"
    },
    "update": {
      "module": "ComplianceManagement",
      "action": "update"
    },
    "delete": {
      "module": "ComplianceManagement",
      "action": "delete"
    },
    "configure": {
      "module": "ComplianceManagement",
      "action": "configure"
    },
    "sendNotification": {
      "module": "ComplianceManagement",
      "action": "sendNotification"
    }
  },
  "DocumentManagement": {
    "upload": {
      "module": "DocumentManagement",
      "action": "upload"
    },
    "download": {
      "module": "DocumentManagement",
      "action": "download"
    },
    "delete": {
      "module": "DocumentManagement",
      "action": "delete"
    },
    "share": {
      "module": "DocumentManagement",
      "action": "share"
    },
    "configure": {
      "module": "DocumentManagement",
      "action": "configure"
    },
    "view": {
      "module": "DocumentManagement",
      "action": "view"
    }
  },
  "NotificationCenter": {
    "view": {
      "module": "NotificationCenter",
      "action": "view"
    },
    "create": {
      "module": "NotificationCenter",
      "action": "create"
    },
    "sendNotification": {
      "module": "NotificationCenter",
      "action": "sendNotification"
    },
    "configure": {
      "module": "NotificationCenter",
      "action": "configure"
    },
    "restore": {
      "module": "NotificationCenter",
      "action": "restore"
    },
    "permanentDelete": {
      "module": "NotificationCenter",
      "action": "permanentDelete"
    }
  },
  "ReportManagement": {
    "view": {
      "module": "ReportManagement",
      "action": "view"
    },
    "generate": {
      "module": "ReportManagement",
      "action": "generate"
    },
    "export": {
      "module": "ReportManagement",
      "action": "export"
    },
    "configure": {
      "module": "ReportManagement",
      "action": "configure"
    }
  },
  "AuditLogs": {
    "view": {
      "module": "AuditLogs",
      "action": "view"
    },
    "filter": {
      "module": "AuditLogs",
      "action": "filter"
    },
    "export": {
      "module": "AuditLogs",
      "action": "export"
    },
    "monitor": {
      "module": "AuditLogs",
      "action": "monitor"
    }
  },
  "TrackingAndAudit": {
    "view": {
      "module": "TrackingAndAudit",
      "action": "view"
    },
    "export": {
      "module": "TrackingAndAudit",
      "action": "export"
    }
  },
  "DashboardAnalytics": {
    "view": {
      "module": "DashboardAnalytics",
      "action": "view"
    },
    "configure": {
      "module": "DashboardAnalytics",
      "action": "configure"
    },
    "download": {
      "module": "DashboardAnalytics",
      "action": "download"
    },
    "monitor": {
      "module": "DashboardAnalytics",
      "action": "monitor"
    }
  },
  "SystemSettings": {
    "configure": {
      "module": "SystemSettings",
      "action": "configure"
    },
    "manageRoles": {
      "module": "SystemSettings",
      "action": "manageRoles"
    },
    "manageIntegrations": {
      "module": "SystemSettings",
      "action": "manageIntegrations"
    },
    "backupRestore": {
      "module": "SystemSettings",
      "action": "backupRestore"
    }
  },
  "SupportHelpdesk": {
    "view": {
      "module": "SupportHelpdesk",
      "action": "view"
    },
    "update": {
      "module": "SupportHelpdesk",
      "action": "update"
    },
    "assign": {
      "module": "SupportHelpdesk",
      "action": "assign"
    },
    "close": {
      "module": "SupportHelpdesk",
      "action": "close"
    },
    "sendNotification": {
      "module": "SupportHelpdesk",
      "action": "sendNotification"
    }
  },
  "AccessControl": {
    "grantAccess": {
      "module": "AccessControl",
      "action": "grantAccess"
    },
    "revokeAccess": {
      "module": "AccessControl",
      "action": "revokeAccess"
    },
    "setRestrictions": {
      "module": "AccessControl",
      "action": "setRestrictions"
    },
    "controlSessions": {
      "module": "AccessControl",
      "action": "controlSessions"
    }
  },
  "FileManagement": {
    "view": {
      "module": "FileManagement",
      "action": "view"
    },
    "create": {
      "module": "FileManagement",
      "action": "create"
    },
    "update": {
      "module": "FileManagement",
      "action": "update"
    },
    "delete": {
      "module": "FileManagement",
      "action": "delete"
    },
    "convert": {
      "module": "FileManagement",
      "action": "convert"
    },
    "download": {
      "module": "FileManagement",
      "action": "download"
    },
    "share": {
      "module": "FileManagement",
      "action": "share"
    }
  },
  "PlacesAndMaps": {
    "view": {
      "module": "PlacesAndMaps",
      "action": "view"
    },
    "autocomplete": {
      "module": "PlacesAndMaps",
      "action": "autocomplete"
    },
    "configure": {
      "module": "PlacesAndMaps",
      "action": "configure"
    }
  }
} as const satisfies Record<
  string,
  Record<string, PermPair>
>;

// Convenience helpers (optional):
export type PermModule = keyof typeof PERM;
export type PermAction<M extends PermModule> = keyof (typeof PERM)[M];

// Example:
//   const canDelete: PermPair = PERM.TeamManagement.delete;

