/* eslint-disable */
// ============================================================================
// AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
// Generated by: tools/gen-permissions.mjs
//
// Purpose:
//   IDE-friendly permission constants for templates/components.
//
// Usage:
//   PERM.TeamManagement.view
//   PERM.TeamManagement.delete
// ============================================================================

export type PermPair = Readonly<{ module: string; action: string }>;

export const PERM = {
  "UserManagement": {
    "view": {
      "module": "UserManagement",
      "action": "view"
    },
    "create": {
      "module": "UserManagement",
      "action": "create"
    },
    "update": {
      "module": "UserManagement",
      "action": "update"
    },
    "delete": {
      "module": "UserManagement",
      "action": "delete"
    },
    "activate": {
      "module": "UserManagement",
      "action": "activate"
    },
    "resetPassword": {
      "module": "UserManagement",
      "action": "resetPassword"
    },
    "assignRole": {
      "module": "UserManagement",
      "action": "assignRole"
    },
    "export": {
      "module": "UserManagement",
      "action": "export"
    },
    "impersonate": {
      "module": "UserManagement",
      "action": "impersonate"
    }
  },
  "PropertyManagement": {
    "view": {
      "module": "PropertyManagement",
      "action": "view"
    },
    "create": {
      "module": "PropertyManagement",
      "action": "create"
    },
    "update": {
      "module": "PropertyManagement",
      "action": "update"
    },
    "delete": {
      "module": "PropertyManagement",
      "action": "delete"
    },
    "assign": {
      "module": "PropertyManagement",
      "action": "assign"
    },
    "upload": {
      "module": "PropertyManagement",
      "action": "upload"
    },
    "publish": {
      "module": "PropertyManagement",
      "action": "publish"
    },
    "configure": {
      "module": "PropertyManagement",
      "action": "configure"
    },
    "export": {
      "module": "PropertyManagement",
      "action": "export"
    }
  },
  "TenantManagement": {
    "view": {
      "module": "TenantManagement",
      "action": "view"
    },
    "create": {
      "module": "TenantManagement",
      "action": "create"
    },
    "update": {
      "module": "TenantManagement",
      "action": "update"
    },
    "delete": {
      "module": "TenantManagement",
      "action": "delete"
    },
    "assign": {
      "module": "TenantManagement",
      "action": "assign"
    },
    "upload": {
      "module": "TenantManagement",
      "action": "upload"
    },
    "sendNotification": {
      "module": "TenantManagement",
      "action": "sendNotification"
    },
    "export": {
      "module": "TenantManagement",
      "action": "export"
    }
  },
  "LeaseManagement": {
    "view": {
      "module": "LeaseManagement",
      "action": "view"
    },
    "create": {
      "module": "LeaseManagement",
      "action": "create"
    },
    "update": {
      "module": "LeaseManagement",
      "action": "update"
    },
    "terminate": {
      "module": "LeaseManagement",
      "action": "terminate"
    },
    "renew": {
      "module": "LeaseManagement",
      "action": "renew"
    },
    "upload": {
      "module": "LeaseManagement",
      "action": "upload"
    },
    "approve": {
      "module": "LeaseManagement",
      "action": "approve"
    },
    "export": {
      "module": "LeaseManagement",
      "action": "export"
    }
  },
  "ComplaintsManagement": {
    "view": {
      "module": "ComplaintsManagement",
      "action": "view"
    },
    "create": {
      "module": "ComplaintsManagement",
      "action": "create"
    },
    "update": {
      "module": "ComplaintsManagement",
      "action": "update"
    },
    "delete": {
      "module": "ComplaintsManagement",
      "action": "delete"
    },
    "assign": {
      "module": "ComplaintsManagement",
      "action": "assign"
    },
    "close": {
      "module": "ComplaintsManagement",
      "action": "close"
    },
    "reopen": {
      "module": "ComplaintsManagement",
      "action": "reopen"
    },
    "export": {
      "module": "ComplaintsManagement",
      "action": "export"
    }
  },
  "PaymentBilling": {
    "view": {
      "module": "PaymentBilling",
      "action": "view"
    },
    "create": {
      "module": "PaymentBilling",
      "action": "create"
    },
    "update": {
      "module": "PaymentBilling",
      "action": "update"
    },
    "delete": {
      "module": "PaymentBilling",
      "action": "delete"
    },
    "recordPayment": {
      "module": "PaymentBilling",
      "action": "recordPayment"
    },
    "refund": {
      "module": "PaymentBilling",
      "action": "refund"
    },
    "reverse": {
      "module": "PaymentBilling",
      "action": "reverse"
    },
    "approve": {
      "module": "PaymentBilling",
      "action": "approve"
    },
    "export": {
      "module": "PaymentBilling",
      "action": "export"
    },
    "configure": {
      "module": "PaymentBilling",
      "action": "configure"
    }
  },
  "TeamManagement.Teams": {
    "view": {
      "module": "TeamManagement.Teams",
      "action": "view"
    },
    "create": {
      "module": "TeamManagement.Teams",
      "action": "create"
    },
    "update": {
      "module": "TeamManagement.Teams",
      "action": "update"
    },
    "delete": {
      "module": "TeamManagement.Teams",
      "action": "delete"
    },
    "assignMembers": {
      "module": "TeamManagement.Teams",
      "action": "assignMembers"
    },
    "assignCaptain": {
      "module": "TeamManagement.Teams",
      "action": "assignCaptain"
    },
    "upload": {
      "module": "TeamManagement.Teams",
      "action": "upload"
    },
    "generate": {
      "module": "TeamManagement.Teams",
      "action": "generate"
    },
    "lock": {
      "module": "TeamManagement.Teams",
      "action": "lock"
    },
    "unlock": {
      "module": "TeamManagement.Teams",
      "action": "unlock"
    },
    "export": {
      "module": "TeamManagement.Teams",
      "action": "export"
    },
    "monitor": {
      "module": "TeamManagement.Teams",
      "action": "monitor"
    }
  },
  "TeamManagement.WorkItems": {
    "view": {
      "module": "TeamManagement.WorkItems",
      "action": "view"
    },
    "create": {
      "module": "TeamManagement.WorkItems",
      "action": "create"
    },
    "update": {
      "module": "TeamManagement.WorkItems",
      "action": "update"
    },
    "delete": {
      "module": "TeamManagement.WorkItems",
      "action": "delete"
    },
    "assign": {
      "module": "TeamManagement.WorkItems",
      "action": "assign"
    },
    "changeStatus": {
      "module": "TeamManagement.WorkItems",
      "action": "changeStatus"
    },
    "prioritize": {
      "module": "TeamManagement.WorkItems",
      "action": "prioritize"
    },
    "uploadEvidence": {
      "module": "TeamManagement.WorkItems",
      "action": "uploadEvidence"
    },
    "requestApproval": {
      "module": "TeamManagement.WorkItems",
      "action": "requestApproval"
    },
    "approveCompletion": {
      "module": "TeamManagement.WorkItems",
      "action": "approveCompletion"
    },
    "rejectCompletion": {
      "module": "TeamManagement.WorkItems",
      "action": "rejectCompletion"
    },
    "reopen": {
      "module": "TeamManagement.WorkItems",
      "action": "reopen"
    },
    "monitor": {
      "module": "TeamManagement.WorkItems",
      "action": "monitor"
    },
    "export": {
      "module": "TeamManagement.WorkItems",
      "action": "export"
    }
  },
  "TeamManagement.WorkEvents": {
    "view": {
      "module": "TeamManagement.WorkEvents",
      "action": "view"
    },
    "create": {
      "module": "TeamManagement.WorkEvents",
      "action": "create"
    },
    "update": {
      "module": "TeamManagement.WorkEvents",
      "action": "update"
    },
    "delete": {
      "module": "TeamManagement.WorkEvents",
      "action": "delete"
    },
    "assign": {
      "module": "TeamManagement.WorkEvents",
      "action": "assign"
    },
    "acknowledge": {
      "module": "TeamManagement.WorkEvents",
      "action": "acknowledge"
    },
    "resolve": {
      "module": "TeamManagement.WorkEvents",
      "action": "resolve"
    },
    "reopen": {
      "module": "TeamManagement.WorkEvents",
      "action": "reopen"
    },
    "uploadEvidence": {
      "module": "TeamManagement.WorkEvents",
      "action": "uploadEvidence"
    },
    "monitor": {
      "module": "TeamManagement.WorkEvents",
      "action": "monitor"
    },
    "export": {
      "module": "TeamManagement.WorkEvents",
      "action": "export"
    }
  },
  "CommentEngine": {
    "view": {
      "module": "CommentEngine",
      "action": "view"
    },
    "create": {
      "module": "CommentEngine",
      "action": "create"
    },
    "updateOwn": {
      "module": "CommentEngine",
      "action": "updateOwn"
    },
    "deleteOwn": {
      "module": "CommentEngine",
      "action": "deleteOwn"
    },
    "moderate": {
      "module": "CommentEngine",
      "action": "moderate"
    },
    "upload": {
      "module": "CommentEngine",
      "action": "upload"
    },
    "pin": {
      "module": "CommentEngine",
      "action": "pin"
    },
    "unpin": {
      "module": "CommentEngine",
      "action": "unpin"
    },
    "pinToggle": {
      "module": "CommentEngine",
      "action": "pinToggle"
    }
  },
  "KpiMonitoring": {
    "view": {
      "module": "KpiMonitoring",
      "action": "view"
    },
    "create": {
      "module": "KpiMonitoring",
      "action": "create"
    },
    "update": {
      "module": "KpiMonitoring",
      "action": "update"
    },
    "export": {
      "module": "KpiMonitoring",
      "action": "export"
    },
    "configure": {
      "module": "KpiMonitoring",
      "action": "configure"
    }
  },
  "AuditLogs": {
    "view": {
      "module": "AuditLogs",
      "action": "view"
    },
    "filter": {
      "module": "AuditLogs",
      "action": "filter"
    },
    "export": {
      "module": "AuditLogs",
      "action": "export"
    },
    "monitor": {
      "module": "AuditLogs",
      "action": "monitor"
    }
  },
  "SystemSettings": {
    "configure": {
      "module": "SystemSettings",
      "action": "configure"
    },
    "manageRoles": {
      "module": "SystemSettings",
      "action": "manageRoles"
    },
    "manageIntegrations": {
      "module": "SystemSettings",
      "action": "manageIntegrations"
    },
    "backupRestore": {
      "module": "SystemSettings",
      "action": "backupRestore"
    }
  },
  "AccessControl": {
    "grantAccess": {
      "module": "AccessControl",
      "action": "grantAccess"
    },
    "revokeAccess": {
      "module": "AccessControl",
      "action": "revokeAccess"
    },
    "setRestrictions": {
      "module": "AccessControl",
      "action": "setRestrictions"
    },
    "controlSessions": {
      "module": "AccessControl",
      "action": "controlSessions"
    },
    "auditChanges": {
      "module": "AccessControl",
      "action": "auditChanges"
    }
  },
  "NotificationCenter": {
    "view": {
      "module": "NotificationCenter",
      "action": "view"
    },
    "markRead": {
      "module": "NotificationCenter",
      "action": "markRead"
    },
    "delete": {
      "module": "NotificationCenter",
      "action": "delete"
    },
    "restore": {
      "module": "NotificationCenter",
      "action": "restore"
    },
    "clear": {
      "module": "NotificationCenter",
      "action": "clear"
    },
    "broadcast": {
      "module": "NotificationCenter",
      "action": "broadcast"
    },
    "configure": {
      "module": "NotificationCenter",
      "action": "configure"
    }
  }
} as const satisfies Record<
  string,
  Record<string, PermPair>
>;

// Convenience helpers (optional):
export type PermModule = keyof typeof PERM;
export type PermAction<M extends PermModule> = keyof (typeof PERM)[M];

// Example:
//   const canDelete: PermPair = PERM.TeamManagement.delete;

